name: lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_run:
    workflows: ["Dependabot PR Workflow"]
    branches:
      - 'dependabot/**'
    types:
      - requested
      
jobs:
  delint:
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'dependabot[bot]' && (github.event.action == 'requested' || github.event.action == 'completed')) || (github.actor != 'dependabot[bot]') }}
    steps:
      - name: Checkout Code for dependabot PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Check out Code
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v2
        
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
